<style>
    .nwl{--nwl-border:#d8dee8;--nwl-muted:#667085;--nwl-text:#182230;--nwl-bg:#fff;--nwl-soft:#f7f8fa;--nwl-accent:#2563eb;--nwl-danger:#b42318;--nwl-success:#067647;--nwl-warning:#b54708;font-family:ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:var(--nwl-text)}
    .nwl *{box-sizing:border-box}.nwl__shell{border:1px solid var(--nwl-border);border-radius:16px;background:var(--nwl-bg);overflow:hidden;box-shadow:0 10px 30px rgba(16,24,40,.05)}
    .nwl__head{display:flex;justify-content:space-between;align-items:flex-start;gap:18px;padding:22px 24px;border-bottom:1px solid var(--nwl-border);background:linear-gradient(180deg,#fff,var(--nwl-soft))}.nwl__title{margin:0;font-size:22px}.nwl__lead{max-width:760px;margin:7px 0 0;color:var(--nwl-muted);line-height:1.5}
    .nwl__locale{min-width:145px}.nwl label{display:block;margin-bottom:6px;font-size:12px;font-weight:700;color:var(--nwl-muted)}.nwl input,.nwl select{width:100%;min-height:40px;padding:8px 10px;border:1px solid var(--nwl-border);border-radius:9px;background:#fff;color:var(--nwl-text);font:inherit;outline:none}.nwl input:focus,.nwl select:focus{border-color:var(--nwl-accent);box-shadow:0 0 0 3px rgba(37,99,235,.12)}
    .nwl__body{padding:20px 24px 24px}.nwl__filters{display:grid;grid-template-columns:minmax(240px,1fr) repeat(2,minmax(145px,220px));gap:12px;margin-bottom:18px}.nwl__filters--system{grid-template-columns:minmax(220px,1fr) minmax(130px,180px) minmax(130px,180px) minmax(220px,1fr)}
    .nwl__notice{padding:13px 15px;border:1px solid #bfdbfe;border-radius:10px;background:#eff6ff;color:#1d4ed8;font-size:13px;line-height:1.5}.nwl__notice--success{border-color:#abefc6;background:#ecfdf3;color:var(--nwl-success)}.nwl__notice--danger{border-color:#fecdca;background:#fef3f2;color:var(--nwl-danger)}
    .nwl__tablewrap{overflow:auto;border:1px solid var(--nwl-border);border-radius:12px}.nwl__table{width:100%;border-collapse:collapse;min-width:850px}.nwl__table th{padding:10px 12px;background:var(--nwl-soft);border-bottom:1px solid var(--nwl-border);color:var(--nwl-muted);font-size:11px;letter-spacing:.04em;text-align:left;text-transform:uppercase}.nwl__table td{padding:12px;border-bottom:1px solid var(--nwl-border);font-size:13px;vertical-align:top}.nwl__table tr:last-child td{border-bottom:0}.nwl__table tbody tr:hover{background:#fafbfc}
    .nwl__mono{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:12px;overflow-wrap:anywhere}.nwl__muted{color:var(--nwl-muted)}.nwl__strong{font-weight:700}.nwl__nowrap{white-space:nowrap}
    .nwl__badge{display:inline-flex;align-items:center;min-height:24px;padding:3px 8px;border:1px solid var(--nwl-border);border-radius:999px;background:#fff;font-size:11px;font-weight:750;white-space:nowrap}.nwl__badge--ok{border-color:#abefc6;background:#ecfdf3;color:var(--nwl-success)}.nwl__badge--warn{border-color:#fedf89;background:#fffaeb;color:var(--nwl-warning)}.nwl__badge--bad{border-color:#fecdca;background:#fef3f2;color:var(--nwl-danger)}.nwl__badge--info{border-color:#bfdbfe;background:#eff6ff;color:#1d4ed8}
    .nwl__button{display:inline-flex;align-items:center;justify-content:center;min-height:38px;padding:7px 12px;border:1px solid var(--nwl-border);border-radius:9px;background:#fff;color:var(--nwl-text);font:inherit;font-size:13px;font-weight:700;cursor:pointer}.nwl__button:hover{border-color:#98a2b3}.nwl__button--primary{border-color:var(--nwl-accent);background:var(--nwl-accent);color:#fff}.nwl__button--danger{border-color:#fda29b;background:#fff;color:var(--nwl-danger)}.nwl__button[disabled]{opacity:.5;cursor:not-allowed}
    .nwl__pager{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-top:14px;color:var(--nwl-muted);font-size:13px}.nwl__actions{display:flex;align-items:center;gap:8px;flex-wrap:wrap}
    .nwl__details{margin-top:18px;border:1px solid var(--nwl-border);border-radius:12px;background:#fff;overflow:hidden}.nwl__detailshead{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:14px 16px;border-bottom:1px solid var(--nwl-border);background:var(--nwl-soft)}.nwl__detailshead h3{margin:0;font-size:16px}.nwl__detailsbody{padding:16px}.nwl__grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.nwl__field{min-width:0}.nwl__field--full{grid-column:1/-1}.nwl__field dt{margin-bottom:5px;color:var(--nwl-muted);font-size:11px;font-weight:750;text-transform:uppercase}.nwl__field dd{margin:0;font-size:13px;line-height:1.5;overflow-wrap:anywhere}.nwl__code{max-height:360px;margin:0;padding:13px;border:1px solid var(--nwl-border);border-radius:9px;background:#111827;color:#e5e7eb;overflow:auto;font:12px/1.55 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;white-space:pre-wrap;word-break:break-word}
    .nwl__entries{display:grid;gap:10px}.nwl__entry{border:1px solid var(--nwl-border);border-radius:11px;overflow:hidden}.nwl__entryhead{display:flex;align-items:center;gap:8px;padding:9px 12px;background:var(--nwl-soft);border-bottom:1px solid var(--nwl-border);font-size:12px}.nwl__entrytime{margin-left:auto;color:var(--nwl-muted)}.nwl__entry pre{margin:0;padding:12px;background:#fff;color:var(--nwl-text);font:12px/1.55 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;white-space:pre-wrap;word-break:break-word}
    .nwl__filemeta{display:flex;flex-wrap:wrap;gap:8px;margin:-4px 0 14px}.nwl__empty{padding:32px 16px;text-align:center;color:var(--nwl-muted)}
    @media(max-width:760px){.nwl__head{flex-direction:column}.nwl__locale{width:100%}.nwl__filters,.nwl__filters--system{grid-template-columns:1fr}.nwl__grid{grid-template-columns:1fr}.nwl__field--full{grid-column:auto}.nwl__pager{align-items:stretch;flex-direction:column}.nwl__pager .nwl__actions{justify-content:space-between}}
</style>
